improv

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,7 +1,7 @@
 #!/sbin/sh
-# Kopi Installer V1.2
+# Kopi Installer V1.4
 # Since 08-05-2020
-# Latest Update 04-04-2021
+# Latest Update 09-06-2021
 # by wahyu6070 (dont change)
 
 OUTFD=/proc/self/fd/$2;
@@ -144,154 +144,167 @@ set_prop() {
     echo "${property}=${value}" >>"${file_location}"
   fi
 }
-find_slot() {
-  local slot=$(getprop ro.boot.slot_suffix 2>/dev/null)
-  [ "$slot" ] || slot=$(grep -o 'androidboot.slot_suffix=.*$' /proc/cmdline | cut -d\  -f1 | cut -d= -f2)
-  if [ ! "$slot" ]; then
-    slot=$(getprop ro.boot.slot 2>/dev/null)
-    [ "$slot" ] || slot=$(grep -o 'androidboot.slot=.*$' /proc/cmdline | cut -d\  -f1 | cut -d= -f2)
-    [ "$slot" ] && slot=_$slot
-  fi
-  [ "$slot" ] && echo "$slot"
-}
-
-setup_mountpoint() {
-  [ -L $1 ] && mv -f $1 ${1}_link
-  if [ ! -d $1 ]; then
-    rm -f $1
-    mkdir -p $1
-  fi
-}
-
 is_mounted() { mount | grep -q " $1 "; }
 
+setup_mountpoint() {
+  test -L $1 && mv -f $1 ${1}_link
+  if [ ! -d $1 ]; then
+    rm -f $1
+    mkdir $1
+  fi
+}
+
 mount_apex() {
-  [ -d /system_root/system/apex ] || return 1
-  local apex dest loop minorx num
-  setup_mountpoint /apex
-  minorx=1
-  [ -e /dev/block/loop1 ] && minorx=$(ls -l /dev/block/loop1 | awk '{ print $6 }')
-  num=0
-  for apex in /system_root/system/apex/*; do
-    dest=/apex/$(basename $apex .apex)
-    [ "$dest" = /apex/com.android.runtime.release ] && dest=/apex/com.android.runtime
-    mkdir -p $dest
-    case $apex in
-      *.apex)
-        unzip -qo $apex apex_payload.img -d /apex
-        mv -f /apex/apex_payload.img $dest.img
-        mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null
-        if [ $? != 0 ]; then
-          while [ $num -lt 64 ]; do
-            loop=/dev/block/loop$num
-            (mknod $loop b 7 $((num * minorx))
-            losetup $loop $dest.img) 2>/dev/null
-            num=$((num + 1))
-            losetup $loop | grep -q $dest.img && break
-          done
-          mount -t ext4 -o ro,loop,noatime $loop $dest
+  # For reference, check: https://github.com/osm0sis/AnyKernel3/blob/master/META-INF/com/google/android/update-binary
+  if [ -d $SYSTEM/apex ]; then
+    local apex dest loop minorx num
+    setup_mountpoint /apex
+    test -e /dev/block/loop1 && minorx=$(ls -l /dev/block/loop1 | awk '{ print $6 }') || minorx=1
+    num=0
+    for apex in $SYSTEM/apex/*; do
+      dest=/apex/$(basename $apex .apex)
+      test "$dest" = /apex/com.android.runtime.release && dest=/apex/com.android.runtime
+      mkdir -p $dest
+      case $apex in
+        *.apex)
+          unzip -qo $apex apex_payload.img -d /apex
+          mv -f /apex/apex_payload.img $dest.img
+          mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null
           if [ $? != 0 ]; then
-            losetup -d $loop 2>/dev/null
+            while [ $num -lt 64 ]; do
+              loop=/dev/block/loop$num
+              (mknod $loop b 7 $((num * minorx))
+              losetup $loop $dest.img) 2>/dev/null
+              num=$((num + 1))
+              losetup $loop | grep -q $dest.img && break
+            done
+            mount -t ext4 -o ro,loop,noatime $loop $dest
+            if [ $? != 0 ]; then
+              losetup -d $loop 2>/dev/null
+            fi
           fi
-        fi
-      ;;
-      *) mount -o bind $apex $dest;;
-    esac
-  done
-  export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
-  export ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
-  export BOOTCLASSPATH=/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/system/framework/telephony-ext.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar
+        ;;
+        *) mount -o bind $apex $dest;;
+      esac
+    done
+    export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
+    export ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
+    export BOOTCLASSPATH=/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar
+  fi
 }
 
-umount_apex() {
-  [ -d /apex ] || return 1
-  local dest loop
-  for dest in $(find /apex -type d -mindepth 1 -maxdepth 1); do
-    if [ -f $dest.img ]; then
-      loop=$(mount | grep $dest | cut -d" " -f1)
+unmount_apex() {
+  if [ -d $SYSTEM/apex ]; then
+    local dest loop
+    for dest in $(find /apex -type d -mindepth 1 -maxdepth 1); do
+      if [ -f $dest.img ]; then
+        loop=$(mount | grep $dest | cut -d" " -f1)
+      fi
+      (umount -l $dest
+      losetup -d $loop) 2>/dev/null
+    done
+    rm -rf /apex 2>/dev/null
+    unset ANDROID_RUNTIME_ROOT ANDROID_TZDATA_ROOT BOOTCLASSPATH
+  fi
+}
+
+
+########################################
+#   Mount Partipations
+########################################
+ui_print "- Mounting partitions"
+if ! $BOOTMODE; then
+  DYNAMIC_PARTITIONS=`getprop ro.boot.dynamic_partitions`
+  SLOT=`getprop ro.boot.slot_suffix`
+  [ ! -z "$SLOT" ] && ui_print "- Current boot slot: $SLOT"
+
+  if [ -n "$(cat /etc/fstab | grep /system_root)" ]; then
+    MOUNT_POINT=/system_root
+  else
+    MOUNT_POINT=/system
+  fi
+
+  for p in "/cache" "/data" "$MOUNT_POINT" "/product" "/system_ext" "/vendor"; do
+    if [ -d "$p" ] && grep -q "$p" "/etc/fstab" && ! is_mounted "$p"; then
+      mount "$p"
     fi
-    (umount -l $dest
-    losetup -d $loop) 2>/dev/null
   done
-  rm -rf /apex 2>/dev/null
-  unset ANDROID_RUNTIME_ROOT ANDROID_TZDATA_ROOT BOOTCLASSPATH
-}
 
-mount_all() {
-  if ! is_mounted /cache; then
-    mount /cache 2>/dev/null && UMOUNT_CACHE=1
+  if [ "$DYNAMIC_PARTITIONS" = "true" ]; then
+    ui_print "- Dynamic partition detected"
+    for m in "/system" "/system_root" "/product" "/system_ext" "/vendor"; do
+      (umount "$m"
+      umount -l "$m") 2>/dev/null
+    done
+    mount -o ro -t auto /dev/block/mapper/system$SLOT /system_root
+    mount -o ro -t auto /dev/block/mapper/vendor$SLOT /vendor 2>/dev/null
+    mount -o ro -t auto /dev/block/mapper/product$SLOT /product 2>/dev/null
+    mount -o ro -t auto /dev/block/mapper/system_ext$SLOT /system_ext 2>/dev/null
+  else
+    mount -o ro -t auto /dev/block/bootdevice/by-name/system$SLOT $MOUNT_POINT 2>/dev/null
   fi
-  if ! is_mounted /data; then
-    mount /data && UMOUNT_DATA=1
+
+  if [ "$DYNAMIC_PARTITIONS" = "true" ]; then
+    for block in system vendor product system_ext; do
+      for slot in "" _a _b; do
+        blockdev --setrw /dev/block/mapper/$block$slot 2>/dev/null
+      done
+    done
+    mount -o rw,remount -t auto /dev/block/mapper/system$SLOT /system_root
+    mount -o rw,remount -t auto /dev/block/mapper/vendor$SLOT /vendor 2>/dev/null
+    mount -o rw,remount -t auto /dev/block/mapper/product$SLOT /product 2>/dev/null
+    mount -o rw,remount -t auto /dev/block/mapper/system_ext$SLOT /system_ext 2>/dev/null
+  else
+    mount -o rw,remount -t auto $MOUNT_POINT
+    mount -o rw,remount -t auto /vendor 2>/dev/null
+    mount -o rw,remount -t auto /product 2>/dev/null
+    mount -o rw,remount -t auto /system_ext 2>/dev/null
   fi
-  (mount -o ro -t auto /vendor
-  mount -o ro -t auto /product
-  mount -o ro -t auto /persist) 2>/dev/null
-  setup_mountpoint $ANDROID_ROOT
-  if ! is_mounted $ANDROID_ROOT; then
-    mount -o ro -t auto $ANDROID_ROOT 2>/dev/null
-  fi
-  case $ANDROID_ROOT in
-    /system_root) setup_mountpoint /system;;
-    /system)
-      if ! is_mounted /system && ! is_mounted /system_root; then
-        setup_mountpoint /system_root
-        mount -o ro -t auto /system_root
-      elif [ -f /system/system/build.prop ]; then
-        setup_mountpoint /system_root
-        mount --move /system /system_root
-      fi
-      if [ $? != 0 ]; then
-        (umount /system
-        umount -l /system) 2>/dev/null
-        if [ -d /dev/block/mapper ]; then
-          [ -e /dev/block/mapper/system ] || local slot=$(find_slot)
-          mount -o ro -t auto /dev/block/mapper/vendor$slot /vendor
-          mount -o ro -t auto /dev/block/mapper/product$slot /product 2>/dev/null
-          mount -o ro -t auto /dev/block/mapper/system$slot /system_root
-        else
-          [ -e /dev/block/bootdevice/by-name/system ] || local slot=$(find_slot)
-          (mount -o ro -t auto /dev/block/bootdevice/by-name/vendor$slot /vendor
-          mount -o ro -t auto /dev/block/bootdevice/by-name/product$slot /product
-          mount -o ro -t auto /dev/block/bootdevice/by-name/persist$slot /persist) 2>/dev/null
-          mount -o ro -t auto /dev/block/bootdevice/by-name/system$slot /system_root
-        fi
-      fi
-    ;;
-  esac
+  
   if is_mounted /system_root; then
-    mount_apex
+    print "- Device is system-as-root"
     if [ -f /system_root/build.prop ]; then
       mount -o bind /system_root /system
+      SYSTEM=/system_root
+      ui_print "- System is $SYSTEM"
     else
       mount -o bind /system_root/system /system
+      SYSTEM=/system_root/system
+      ui_print "- System is $SYSTEM"
     fi
+  elif is_mounted /system; then
+    if [ -f /system/build.prop ]; then
+      SYSTEM=/system
+      ui_print "- System is $SYSTEM"
+    elif [ -f /system/system/build.prop ]; then
+      ui_print "- Device is system-as-root"
+      mkdir -p /system_root
+      mount --move /system /system_root
+      mount -o bind /system_root/system /system
+      SYSTEM=/system_root/system
+      ui_print "- System is /system/system"
+    fi
+  else
+    abort "- Failed to mounting <system>"
   fi
-}
-
-umount_all() {
-  local mount
-  (umount /system
-  umount -l /system
-  if [ -e /system_root ]; then
-    umount /system_root
-    umount -l /system_root
-  fi
-  umount_apex
-  for mount in /mnt/system /vendor /mnt/vendor /product /mnt/product /persist; do
-    umount $mount
-    umount -l $mount
+  for MOUNT6070 in /vendor /data /cache; do
+		if $is_mounted $MOUNT6070; then
+			mount -o rw,remount $MOUNT6070 || mount $MOUNT6070 || mount -o rw,remount -t auto $MOUNT6070 || mount -o rw,remount / || abort "- Abort mounting $MOUNT6070"
+		fi
   done
-  if [ "$UMOUNT_DATA" ]; then
-    umount /data
-    umount -l /data
-  fi
-  if [ "$UMOUNT_CACHE" ]; then
-    umount /cache
-    umount -l /cache
-  fi) 2>/dev/null
-}
-
+  mount_apex
+else
+	mount -o rw,remount /system || mount /system || mount -o rw,remount -t auto /system || mount -o rw,remount / || abort "- Abort mounting system"
+	mount -o rw,remount /vendor || mount /vendor || mount -o rw,remount -t auto /vendor || mount -o rw,remount / || abort "- Abort mounting vendor"
+fi
+#RECOVERY ACTIONS
+OLD_LD_LIB=$LD_LIBRARY_PATH
+OLD_LD_PRE=$LD_PRELOAD
+OLD_LD_CFG=$LD_CONFIG_FILE
+unset LD_LIBRARY_PATH
+unset LD_PRELOAD
+unset LD_CONFIG_FILE
+set_progress 0.4;
 ########################################
 #    Kopi Script
 ########################################
@@ -301,33 +314,6 @@ print " ";
 print "- Kopi Installer by wahyu6070";
 print " "
 show_progress 1.34 0;
-
-#mount
-print "- Mounting"
-[ "$ANDROID_ROOT" ] || ANDROID_ROOT=/system
-
-# emulators can only flash booted and may need /system (on legacy images), or / (on system-as-root images), remounted rw
-if ! $BOOTMODE; then
-  mount -o bind /dev/urandom /dev/random
-  if [ -L /etc ]; then
-    setup_mountpoint /etc
-    cp -af /etc_link/* /etc
-    sed -i 's; / ; /system_root ;' /etc/fstab
-  fi
-  umount_all
-  mount_all
-fi
-if [ -d /dev/block/mapper ]; then
-  for block in system vendor product; do
-    for slot in "" _a _b; do
-      blockdev --setrw /dev/block/mapper/$block$slot 2>/dev/null
-    done
-  done
-fi
-mount -o rw,remount -t auto /system || mount -o rw,remount -t auto /
-(mount -o rw,remount -t auto /vendor
-mount -o rw,remount -t auto /product) 2>/dev/null
-set_progress 0.4;
 
 #system dir
 if [ -f /system/system/build.prop ]; then
@@ -374,6 +360,7 @@ DATE=`getp date $MODULE`
 AUTHOR=`getp author $MODULE`
 KOPIMOD=/data/kopi/modules/"$ID"
 MAGISKMOD=/data/adb/modules/$ID
+MAGISKUP="/data/adb/modules_update/$ID"
 set_progress 0.5;
 
 #req
@@ -410,22 +397,43 @@ else
 	magisk)
 	print "- Type Magisk Module"
 	[ -f /data/adb/magisk/util_functions.sh ] && [ $TYPEINSTALL = magisk ] && . /data/adb/magisk/util_functions.sh
-	modup="/data/adb/modules_update/$ID"
-	del $modup
-	cdir "$modup"
+	del $MAGISKUP
+	cdir "$MAGISKUP"
 	cdir "/data/adb/modules/$ID"
 	touch "/data/adb/modules/$ID/update"
 	cp -pf $kopi/module.prop "/data/adb/modules/$ID/"
-	[ -f $kopi/magisk-uninstall.sh ] && cp -pf $kopi/magisk-uninstall.sh $modup/uninstall.sh && chmod 755 $modup/uninstall.sh
-	[ -f $kopi/magisk-system.prop ] && cp -pf $kopi/magisk-system.prop $modup/system.prop
-	[ -f $kopi/magisk-service.sh ] && cp -pf $kopi/magisk-service.sh $modup/service.sh && chmod 755 $modup/service.sh
-	[ -f $kopi/magisk-post-fs-data.sh ] && cp -pf $kopi/magisk-post-fs-data.sh $modup/post-fs-data.sh && chmod 755 $modup/post-fs-data.sh
-	cp -rdf $kopi/* "$modup"
-	del $modup/META-INF
-	del $modup/install.sh
-	del $modup/customize.sh
-	del $modup/install.zip
-	del $modup/README.md
+	if [ -f $kopi/magisk-uninstall.sh ]; then
+		test -f $kopi/uninstall.sh && del $kopi/uninstall.sh
+		cp -pf $kopi/magisk-uninstall.sh $MAGISKUP/uninstall.sh
+		chmod 755 $MAGISKUP/uninstall.sh
+		del $kopi/magisk-uninstall.sh
+	fi
+	if [ -f $kopi/magisk-system.prop ]; then
+		cp -pf $kopi/magisk-system.prop $MAGISKUP/system.prop
+		del $kopi/magisk-system.prop
+	fi
+	if [ -f $kopi/magisk-service.sh ]; then
+		cp -pf $kopi/magisk-service.sh $MAGISKUP/service.sh
+		chmod 755 $MAGISKUP/service.sh
+		del $kopi/magisk-service.sh
+	fi
+	if [ -f $kopi/magisk-post-fs-data.sh ]; then
+		cp -pf $kopi/magisk-post-fs-data.sh $MAGISKUP/post-fs-data.sh
+		chmod 755 $MAGISKUP/post-fs-data.sh
+		del $kopi/magisk-post-fs-data.sh
+	fi
+	cp -rdf $kopi/* "$MAGISKUP"
+	
+	LIST_RM="
+	$MAGISKUP/META-INF
+	$MAGISKUP/install.sh
+	$MAGISKUP/customize.sh
+	$MAGISKUP/install.zip
+	$MAGISKUP/README.md
+	"
+	for W7878 in $LIST_RM; do
+		del $W7878
+	done
 	;;
 	kopi)
 	print "- Type Kopi Module"
@@ -476,15 +484,31 @@ fi
 #permissions
 if [ -f $kopi/permissions.sh ] && [ ! $uninstallmode ]; then
 print "- Set Permissions"
-chmod 775 $kopi/permissions.sh
+chmod 755 $kopi/permissions.sh
 . $kopi/permissions.sh
 fi
 
 #umount
-print "- Umounting";
-if [ $TYPEINSTALL = kopi ]; then
-umount /system
-umount /vendor
+print "- Umounting partitions";
+if ! $BOOTMODE; then
+unmount_apex
+  for UN_MOUNT in /system /system_root /product /system_ext /vendor; do
+  	if [ -e $UN_MOUNT ]; then
+  		(umount $UN_MOUNT
+  		umount -l $UN_MOUNT) 2>/dev/null
+  	fi
+  done
+  
+#RECOVERY CLEANUP
+[ -z $OLD_LD_LIB ] || export LD_LIBRARY_PATH=$OLD_LD_LIB
+[ -z $OLD_LD_PRE ] || export LD_PRELOAD=$OLD_LD_PRE
+[ -z $OLD_LD_CFG ] || export LD_CONFIG_FILE=$OLD_LD_CFG
+else
+  for UN_MOUNT2 in /system /vendor; do
+    if [ -e $UN_MOUNT2 ]; then
+      umount $UN_MOUNT2
+    fi
+  done
 fi
 set_progress 1.1;
 cd /;
