Fix dynamic partition

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,7 +1,7 @@
 #!/sbin/sh
-# Kopi Installer V1.4
+# Kopi Installer V1.5
 # Since 08-05-2020
-# Latest Update 11-06-2021
+# Latest Update 02-10-2021
 # by wahyu6070 (dont change)
 
 OUTFD=/proc/self/fd/$2;
@@ -144,168 +144,248 @@ set_prop() {
     echo "${property}=${value}" >>"${file_location}"
   fi
 }
-is_mounted() { mount | grep -q " $1 "; }
-
-setup_mountpoint() {
-  test -L $1 && mv -f $1 ${1}_link
-  if [ ! -d $1 ]; then
-    rm -f $1
-    mkdir $1
-  fi
-}
-
-mount_apex() {
-  # For reference, check: https://github.com/osm0sis/AnyKernel3/blob/master/META-INF/com/google/android/update-binary
-  if [ -d $SYSTEM/apex ]; then
-    local apex dest loop minorx num
-    setup_mountpoint /apex
-    test -e /dev/block/loop1 && minorx=$(ls -l /dev/block/loop1 | awk '{ print $6 }') || minorx=1
-    num=0
-    for apex in $SYSTEM/apex/*; do
-      dest=/apex/$(basename $apex .apex)
-      test "$dest" = /apex/com.android.runtime.release && dest=/apex/com.android.runtime
-      mkdir -p $dest
-      case $apex in
-        *.apex)
-          unzip -qo $apex apex_payload.img -d /apex
-          mv -f /apex/apex_payload.img $dest.img
-          mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null
-          if [ $? != 0 ]; then
-            while [ $num -lt 64 ]; do
-              loop=/dev/block/loop$num
-              (mknod $loop b 7 $((num * minorx))
-              losetup $loop $dest.img) 2>/dev/null
-              num=$((num + 1))
-              losetup $loop | grep -q $dest.img && break
-            done
-            mount -t ext4 -o ro,loop,noatime $loop $dest
-            if [ $? != 0 ]; then
-              losetup -d $loop 2>/dev/null
-            fi
-          fi
-        ;;
-        *) mount -o bind $apex $dest;;
-      esac
-    done
-    export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
-    export ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
-    export BOOTCLASSPATH=/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar
-  fi
-}
-
-unmount_apex() {
-  if [ -d $SYSTEM/apex ]; then
-    local dest loop
-    for dest in $(find /apex -type d -mindepth 1 -maxdepth 1); do
-      if [ -f $dest.img ]; then
-        loop=$(mount | grep $dest | cut -d" " -f1)
-      fi
-      (umount -l $dest
-      losetup -d $loop) 2>/dev/null
-    done
-    rm -rf /apex 2>/dev/null
-    unset ANDROID_RUNTIME_ROOT ANDROID_TZDATA_ROOT BOOTCLASSPATH
-  fi
-}
-
 
 ########################################
 #   Mount Partipations
 ########################################
-ui_print "- Mounting partitions"
-if ! $BOOTMODE; then
-  DYNAMIC_PARTITIONS=`getprop ro.boot.dynamic_partitions`
-  SLOT=`getprop ro.boot.slot_suffix`
-  [ ! -z "$SLOT" ] && ui_print "- Current boot slot: $SLOT"
+setenforce 0
+# osm0sis : https://github.com/osm0sis/AnyKernel3
+[ -d /postinstall/tmp ] && POSTINSTALL=/postinstall;
+[ "$AKHOME" ] || AKHOME=$POSTINSTALL/tmp/anykernel;
+[ "$ANDROID_ROOT" ] || ANDROID_ROOT=/system;
 
-  if [ -n "$(cat /etc/fstab | grep /system_root)" ]; then
-    MOUNT_POINT=/system_root
-  else
-    MOUNT_POINT=/system
-  fi
 
-  for p in "/cache" "/data" "$MOUNT_POINT" "/product" "/system_ext" "/vendor"; do
-    if [ -d "$p" ] && grep -q "$p" "/etc/fstab" && ! is_mounted "$p"; then
-      mount "$p"
-    fi
-  done
-
-  if [ "$DYNAMIC_PARTITIONS" = "true" ]; then
-    ui_print "- Dynamic partition detected"
-    for m in "/system" "/system_root" "/product" "/system_ext" "/vendor"; do
-      (umount "$m"
-      umount -l "$m") 2>/dev/null
-    done
-    mount -o ro -t auto /dev/block/mapper/system$SLOT /system_root
-    mount -o ro -t auto /dev/block/mapper/vendor$SLOT /vendor 2>/dev/null
-    mount -o ro -t auto /dev/block/mapper/product$SLOT /product 2>/dev/null
-    mount -o ro -t auto /dev/block/mapper/system_ext$SLOT /system_ext 2>/dev/null
-  else
-    mount -o ro -t auto /dev/block/bootdevice/by-name/system$SLOT $MOUNT_POINT 2>/dev/null
-  fi
-
-  if [ "$DYNAMIC_PARTITIONS" = "true" ]; then
+file_getprop() { grep "^$2=" "$1" | cut -d= -f2-; }
+find_slot() {
+  local slot=$(getprop ro.boot.slot_suffix 2>/dev/null);
+  [ "$slot" ] || slot=$(grep -o 'androidboot.slot_suffix=.*$' /proc/cmdline | cut -d\  -f1 | cut -d= -f2);
+  if [ ! "$slot" ]; then
+    slot=$(getprop ro.boot.slot 2>/dev/null);
+    [ "$slot" ] || slot=$(grep -o 'androidboot.slot=.*$' /proc/cmdline | cut -d\  -f1 | cut -d= -f2);
+    [ "$slot" ] && slot=_$slot;
+  fi;
+  [ "$slot" ] && echo "$slot";
+}
+setup_mountpoint() {
+  [ -L $1 ] && mv -f $1 ${1}_link;
+  if [ ! -d $1 ]; then
+    rm -f $1;
+    mkdir -p $1;
+  fi;
+}
+is_mounted() { mount | grep -q " $1 "; }
+mount_apex() {
+  [ -d /system_root/system/apex ] || return 1;
+  local apex dest loop minorx num var;
+  setup_mountpoint /apex;
+  minorx=1;
+  [ -e /dev/block/loop1 ] && minorx=$(ls -l /dev/block/loop1 | awk '{ print $6 }');
+  num=0;
+  for apex in /system_root/system/apex/*; do
+    dest=/apex/$(basename $apex .apex);
+    case $dest in
+      *.current|*.release) dest=$(echo $dest | rev | cut -d. -f2- | rev);;
+    esac;
+    mkdir -p $dest;
+    case $apex in
+      *.apex)
+        unzip -qo $apex apex_payload.img -d /apex;
+        mv -f /apex/apex_payload.img $dest.img;
+        mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null;
+        if [ $? != 0 ]; then
+          while [ $num -lt 64 ]; do
+            loop=/dev/block/loop$num;
+            (mknod $loop b 7 $((num * minorx));
+            losetup $loop $dest.img) 2>/dev/null;
+            num=$((num + 1));
+            losetup $loop | grep -q $dest.img && break;
+          done;
+          mount -t ext4 -o ro,loop,noatime $loop $dest;
+          if [ $? != 0 ]; then
+            losetup -d $loop 2>/dev/null;
+          fi;
+        fi;
+      ;;
+      *) mount -o bind $apex $dest;;
+    esac;
+  done;
+  for var in $(grep -o 'export .* /.*' /system_root/init.environ.rc | awk '{ print $2 }'); do
+    eval OLD_${var}=\$$var;
+  done;
+  $(grep -o 'export .* /.*' /system_root/init.environ.rc | sed 's; /;=/;'); unset export;
+}
+umount_apex() {
+  [ -d /apex/com.android.runtime ] || return 1;
+  local dest loop var;
+  for var in $(grep -o 'export .* /.*' /system_root/init.environ.rc | awk '{ print $2 }'); do
+    if [ "$(eval echo \$OLD_$var)" ]; then
+      eval $var=\$OLD_${var};
+    else
+      eval unset $var;
+    fi;
+    unset OLD_${var};
+  done;
+  for dest in $(find /apex -type d -mindepth 1 -maxdepth 1); do
+    if [ -f $dest.img ]; then
+      loop=$(mount | grep $dest | cut -d\  -f1);
+    fi;
+    (umount -l $dest;
+    losetup -d $loop) 2>/dev/null;
+  done;
+  rm -rf /apex 2>/dev/null;
+}
+mount_all() {
+  if ! is_mounted /cache; then
+     mount /cache 2>/dev/null && UMOUNT_CACHE=1;
+  fi;
+  if ! is_mounted /data; then
+     mount /data && UMOUNT_DATA=1;
+  fi;
+  ( mount -o ro -t auto /vendor;
+   mount -o ro -t auto /product;
+   mount -o ro -t auto /persist) 2>/dev/null;
+  setup_mountpoint $ANDROID_ROOT;
+  if ! is_mounted $ANDROID_ROOT; then
+     mount -o ro -t auto $ANDROID_ROOT 2>/dev/null;
+  fi;
+  case $ANDROID_ROOT in
+    /system_root) setup_mountpoint /system;;
+    /system)
+      if ! is_mounted /system && ! is_mounted /system_root; then
+        setup_mountpoint /system_root;
+         mount -o ro -t auto /system_root;
+      elif [ -f /system/system/build.prop ]; then
+        setup_mountpoint /system_root;
+         mount --move /system /system_root;
+      fi;
+      if [ $? != 0 ]; then
+        ( umount /system;
+         umount -l /system) 2>/dev/null;
+        if [ -d /dev/block/mapper ]; then
+          [ -e /dev/block/mapper/system ] || local slot=$(find_slot);
+           mount -o ro -t auto /dev/block/mapper/vendor$slot /vendor;
+           mount -o ro -t auto /dev/block/mapper/product$slot /product 2>/dev/null;
+           mount -o ro -t auto /dev/block/mapper/system$slot /system_root;
+           mount -o ro -t auto /dev/block/mapper/system_ext$slot /system_ext;
+        else
+          [ -e /dev/block/bootdevice/by-name/system ] || local slot=$(find_slot);
+          ( mount -o ro -t auto /dev/block/bootdevice/by-name/vendor$slot /vendor;
+           mount -o ro -t auto /dev/block/bootdevice/by-name/product$slot /product;
+           mount -o ro -t auto /dev/block/bootdevice/by-name/persist$slot /persist) 2>/dev/null;
+           mount -o ro -t auto /dev/block/bootdevice/by-name/system$slot /system_root;
+        fi;
+      fi;
+    ;;
+  esac;
+  if [ -d /dev/block/mapper ]; then
     for block in system vendor product system_ext; do
       for slot in "" _a _b; do
         blockdev --setrw /dev/block/mapper/$block$slot 2>/dev/null
       done
     done
-    mount -o rw,remount -t auto /dev/block/mapper/system$SLOT /system_root
-    mount -o rw,remount -t auto /dev/block/mapper/vendor$SLOT /vendor 2>/dev/null
-    mount -o rw,remount -t auto /dev/block/mapper/product$SLOT /product 2>/dev/null
-    mount -o rw,remount -t auto /dev/block/mapper/system_ext$SLOT /system_ext 2>/dev/null
-  else
-    mount -o rw,remount -t auto $MOUNT_POINT
-    mount -o rw,remount -t auto /vendor 2>/dev/null
-    mount -o rw,remount -t auto /product 2>/dev/null
-    mount -o rw,remount -t auto /system_ext 2>/dev/null
   fi
-  
   if is_mounted /system_root; then
-    print "- Device is system-as-root"
-    if [ -f /system_root/build.prop ]; then
-      mount -o bind /system_root /system
-      SYSTEM=/system_root
-      ui_print "- System is $SYSTEM"
-    else
-      mount -o bind /system_root/system /system
-      SYSTEM=/system_root/system
-      ui_print "- System is $SYSTEM"
-    fi
-  elif is_mounted /system; then
-    if [ -f /system/build.prop ]; then
-      SYSTEM=/system
-      ui_print "- System is $SYSTEM"
-    elif [ -f /system/system/build.prop ]; then
-      ui_print "- Device is system-as-root"
-      mkdir -p /system_root
-      mount --move /system /system_root
-      mount -o bind /system_root/system /system
-      SYSTEM=/system_root/system
-      ui_print "- System is /system/system"
-    fi
-  else
-    abort "- Failed to mounting <system>"
-  fi
-  for MOUNT6070 in /vendor /data /cache; do
-		if $is_mounted $MOUNT6070; then
-			mount -o rw,remount $MOUNT6070 || mount $MOUNT6070 || mount -o rw,remount -t auto $MOUNT6070 || mount -o rw,remount / || abort "- Abort mounting $MOUNT6070"
-		fi
-  done
-  mount_apex
+    mount_apex;
+    #if [ -f /system_root/build.prop ]; then
+       #mount -o bind /system_root /system;
+    #else
+       #mount -o bind /system_root/system /system;
+    #fi;
+  fi;
+}
+umount_all() {
+  local mount;
+  (if [ ! -d /postinstall/tmp ]; then
+    umount /system;
+    umount -l /system;
+  fi) 2>/dev/null;
+  umount_apex;
+  (if [ ! -d /postinstall/tmp ]; then
+    umount /system_root;
+    umount -l /system_root;
+  fi;
+  umount /vendor; # busybox umount /vendor breaks recovery on some hacky devices
+  umount -l /vendor;
+  for mount in /mnt/system /mnt/vendor /product /mnt/product /system_ext /mnt/system_ext /persist; do
+    umount $mount;
+    umount -l $mount;
+  done;
+  if [ "$UMOUNT_DATA" ]; then
+    umount /data;
+    umount -l /data;
+  fi;
+  if [ "$UMOUNT_CACHE" ]; then
+    umount /cache;
+    umount -l /cache;
+  fi) 2>/dev/null;
+}
+setup_env() {
+  $BOOTMODE && return 1;
+  mount -o bind /dev/urandom /dev/random;
+  if [ -L /etc ]; then
+    setup_mountpoint /etc;
+    cp -af /etc_link/* /etc;
+    sed -i 's; / ; /system_root ;' /etc/fstab;
+  fi;
+  umount_all;
+  mount_all;
+  OLD_LD_PATH=$LD_LIBRARY_PATH;
+  OLD_LD_PRE=$LD_PRELOAD;
+  OLD_LD_CFG=$LD_CONFIG_FILE;
+  unset LD_LIBRARY_PATH LD_PRELOAD LD_CONFIG_FILE;
+  if [ ! "$(getprop 2>/dev/null)" ]; then
+    getprop() {
+      local propdir propfile propval;
+      for propdir in / /system_root /system /vendor /product /system_ext /odm; do
+        for propfile in default.prop build.prop; do
+          if [ "$propval" ]; then
+            break 2;
+          else
+            propval="$(file_getprop $propdir/$propfile $1 2>/dev/null)";
+          fi;
+        done;
+      done;
+      if [ "$propval" ]; then
+        echo "$propval";
+      else
+        echo "";
+      fi;
+    }
+  elif [ ! "$(getprop ro.build.type 2>/dev/null)" ]; then
+    getprop() {
+      ($(which getprop) | grep "$1" | cut -d[ -f3 | cut -d] -f1) 2>/dev/null;
+    }
+  fi;
+}
+restore_env() {
+  $BOOTMODE && return 1;
+  local dir;
+  unset -f getprop;
+  [ "$OLD_LD_PATH" ] && export LD_LIBRARY_PATH=$OLD_LD_PATH;
+  [ "$OLD_LD_PRE" ] && export LD_PRELOAD=$OLD_LD_PRE;
+  [ "$OLD_LD_CFG" ] && export LD_CONFIG_FILE=$OLD_LD_CFG;
+  unset OLD_LD_PATH OLD_LD_PRE OLD_LD_CFG;
+  umount_all;
+  [ -L /etc_link ] && rm -rf /etc/*;
+  (for dir in /etc /apex /system_root /system /vendor /product /system_ext /persist; do
+    if [ -L "${dir}_link" ]; then
+      rmdir $dir;
+      mv -f ${dir}_link $dir;
+    fi;
+  done;
+  umount -l /dev/random) 2>/dev/null;
+}
+
+if $BOOTMODE; then
+	mount -o rw,remount -t auto / || mount -o rw,remount / 2>/dev/null;
 else
-	mount -o rw,remount /system || mount /system || mount -o rw,remount -t auto /system || mount -o rw,remount / || abort "- Abort mounting system"
-	mount -o rw,remount /vendor || mount /vendor || mount -o rw,remount -t auto /vendor || mount -o rw,remount / || abort "- Abort mounting vendor"
+	setup_env
+	for W78 in /system /product /system_ext /system_root /vendor /; do
+		mount -o rw,remount -t auto $W78 2>/dev/null;
+	done
 fi
-#RECOVERY ACTIONS
-OLD_LD_LIB=$LD_LIBRARY_PATH
-OLD_LD_PRE=$LD_PRELOAD
-OLD_LD_CFG=$LD_CONFIG_FILE
-unset LD_LIBRARY_PATH
-unset LD_PRELOAD
-unset LD_CONFIG_FILE
-set_progress 0.4;
-########################################
+
+#########################################
 #    Kopi Script
 ########################################
 	
@@ -330,10 +410,11 @@ fi
 kopi=/dev/tmp/kopi
 MODPATH=$kopi
 TMPDIR=/dev/tmp
-cdir $kopi;
+cdir $kopi || abort "! Failed create $kopi dir"
 cd $kopi
 print "- Extracting ZIP File"
 unzip -o "$ZIPFILE" >&2
+
 [ ! -f module.prop ] && abort "- Module.prop Not Found"
 
 #prop
@@ -374,7 +455,13 @@ if [ $(getp typeinstall $MODULE) = kopi ]; then TYPEINSTALL=kopi
 elif [ $(getp typeinstall $MODULE) = magisk ]; then TYPEINSTALL=magisk
 elif [ $(getp typeinstall $MODULE) = false ]; then TYPEINSTALL=false
 else
-$BOOTMODE && TYPEINSTALL=magisk || [ -f /data/adb/magisk/magisk ] && TYPEINSTALL=magisk || TYPEINSTALL=kopi
+	if $BOOTMODE; then
+		TYPEINSTALL=magisk
+	elif [ -f /data/adb/magisk/util_functions.sh ]; then
+		TYPEINSTALL=magisk
+	else
+		TYPEINSTALL=kopi
+	fi
 fi
 
 # Uninstall
@@ -491,24 +578,7 @@ fi
 #umount
 print "- Umounting partitions";
 if ! $BOOTMODE; then
-unmount_apex
-  for UN_MOUNT in /system /system_root /product /system_ext /vendor; do
-  	if [ -e $UN_MOUNT ]; then
-  		(umount $UN_MOUNT
-  		umount -l $UN_MOUNT) 2>/dev/null
-  	fi
-  done
-  
-#RECOVERY CLEANUP
-[ -z $OLD_LD_LIB ] || export LD_LIBRARY_PATH=$OLD_LD_LIB
-[ -z $OLD_LD_PRE ] || export LD_PRELOAD=$OLD_LD_PRE
-[ -z $OLD_LD_CFG ] || export LD_CONFIG_FILE=$OLD_LD_CFG
-else
-  for UN_MOUNT2 in /system /vendor; do
-    if [ -e $UN_MOUNT2 ]; then
-      umount $UN_MOUNT2
-    fi
-  done
+	restore_env
 fi
 set_progress 1.1;
 cd /;
